Algoritmo "ex001"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2024
Var
// Seção de Declarações das variáveis
   a, b, c, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   leia (a)
      b <- 0
      c <- 0
   para i de 1 ate 5 faca
      b <- b + 2 * a + i
      c <- c + 3 * a - i
      escreval (b + c)
   fimpara
Fimalgoritmo
